build:
  version: "2.0"

accounts:
  message: "Welcome to Bank accounts related QA APIs "
  contactDetails:
    name: "Mac Ray - QA Lead"
    email: "mac@bank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371