spring:
  application:
    name: "config_server"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


#spring:
#  profiles:
#    active:git
#  cloud:
#    config:
#      server:
#        git:
#          uri: "GITHUB REPO "
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true



server:
  port: 8071
